### ISSUE TITLE
Error observed while testing w/ nock

### ISSUE THREAD

**Issue by evansiroky** [olalonde/follow-redirects#48]
I'm getting the following error when running a test that uses [nock](https://github.com/node-nock/nock/).

```
TypeError: Cannot read property '_redirectable' of undefined
      at eventHandlers.(anonymous function) (node_modules/follow-redirects/index.js:22:7)
      at OverriddenClientRequest.RequestOverrider.req.once.req.on (node_modules/nock/lib/request_overrider.js:195:7)
      at Writable.RedirectableRequest._performRequest (node_modules/follow-redirects/index.js:69:12)
      at Writable.RedirectableRequest (node_modules/follow-redirects/index.js:46:7)
      at Object.wrappedProtocol.request (node_modules/follow-redirects/index.js:202:10)
      at Object.wrappedProtocol.get (node_modules/follow-redirects/index.js:207:33)
      at getLatestUrl (lib/update.js:21:13)
      ...
```

The error doesn't happen when I run the program regularly.  See this [travis build](https://travis-ci.org/evansiroky/node-geo-tz/builds/182119016) for more context.

**Comment by RubenVerborgh** [comment]
At the moment, this seems like a nock bug to me; it doesn't set the correct `this` when executing the callback. Could you either file an issue with nock, or write a small reproducible test case here?

**Comment by evansiroky** [comment]
See https://github.com/evansiroky/follow-redirects-nock-bug

**Comment by RubenVerborgh** [comment]
Perfect, thanks!

**Comment by RubenVerborgh** [comment]
It's a nock bug: node-nock/nock#769.

**Comment by wathmal** [comment]
had the same issue, upgrading to latest version fixed it.
