### ISSUE TITLE
Write after end when piping

### ISSUE THREAD

**Issue by rexxars** [olalonde/follow-redirects#50]
I have a fairly simple case where I'm building a tarball-stream on the fly and piping it to a request that's going through `follow-redirects`.

It almost immediately crashes with this error:

```
Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:439:15)
    at Writable.RedirectableRequest._write (/home/espenh/webdev/sanity/cli/node_modules/follow-redirects/index.js:170:23)
    at doWrite (_stream_writable.js:333:12)
    at clearBuffer (_stream_writable.js:440:7)
    at onwrite (_stream_writable.js:372:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at CorkedRequest.finish (_stream_writable.js:547:7)
    at afterWrite (_stream_writable.js:387:3)
    at onwrite (_stream_writable.js:378:7)
    at TLSSocket.WritableState.onwrite (_stream_writable.js:89:5)
```

I'll see if I can find time to write a reduced test case at some point, but don't have time right at this moment. Switching to regular HTTP/HTTPS for this request fixes the problem.

**Comment by RubenVerborgh** [comment]
Thanks for reporting. If you don't find the time for a reduced test case, you can also [send me your current code](https://ruben.verborgh.org/about/email/) in private.

**Comment by RubenVerborgh** [comment]
Closing this because of inactivity.

**Comment by fogine** [comment]
Hello @RubenVerborgh ,

we have reproduced the issue with follow-redirects@1.2.3, [HERE](https://drive.google.com/file/d/0B7wAlEtSWjaaVF8xaTV1Q2I2MlU/view?usp=sharing) is the code.
Run `node index.js`
Substantial information is in the index.js

**Comment by RubenVerborgh** [comment]
Thanks, will have a look.

**Comment by rexxars** [comment]
Thanks for making this reproducible @fogine - I'm sorry I never got around to doing so.

**Comment by olalonde** [comment]
Hey @RubenVerborgh , I also stumbled upon this bug through axios: https://github.com/mzabriskie/axios/issues/964 

Full test case:

```
const test = require('blue-tape')
const axios = require('axios')
const express = require('express')
const { promisify } = require('util')
const concat = require('concat-stream')
const FormData = require('form-data')
const axiosVersion = require('axios/package.json').version

const listen = (app) => new Promise((resolve, reject) => {
  const server = app.listen((err) => {
    if (err) return reject(err)
    resolve(server)
  })
})

let closeServer
let baseURL
let port
let client
let server

const startServer = async () => {
  const app = express()

  app.post('/upload', (req, res) => {
    // console.error(req.headers)
    req.pipe(concat(() => {
      res.json({ headers: req.headers })
    }))
  })

  server = await listen(app)

  closeServer = promisify(server.close.bind(server))
  port = server.address().port
  baseURL = `http://localhost:${port}`
  client = axios.create({
    baseURL,
    /*
    headers: {
      'x-identity-token': 'test123',
    },
    */
  })
  return server
}

test('start server', startServer)

test('upload file', async (t) => {
  const buf = new Buffer('deadbeef', 'hex')
  const form = new FormData()
  form.append('some-image', buf, {
    filename: 'some-image.jpg',
    contentType: 'image/jpeg',
  })

  const headers = form.getHeaders()
  const boundaryId = headers['content-type'].substr(-24)
  t.deepEqual(headers, {
    /* eslint-disable max-len */
    'content-type': `multipart/form-data; boundary=--------------------------${boundaryId}`,
  })

  const response = await client.post('/upload', form, { headers })

  t.deepEqual(response.data, {
    headers: {
      accept: 'application/json, text/plain, */*',
      connection: 'close',
      'content-type': `multipart/form-data; boundary=--------------------------${boundaryId}`,
      host: `localhost:${port}`,
      'transfer-encoding': 'chunked',
      'user-agent': `axios/${axiosVersion}`,
    },
  })
})

test('stop server', async () => {
  await closeServer()
})
```

The bug was introduced by follow-redirects@0.3.0 https://github.com/olalonde/follow-redirects/compare/v0.2.0...v0.3.0

**Comment by RubenVerborgh** [comment]
Thanks. I will create a fix soon.

**Comment by RubenVerborgh** [comment]
This fixes @olalonde's test case. Please verify.

**Comment by olalonde** [comment]
@RubenVerborgh thanks!

**Comment by rwpino** [comment]
https://stackoverflow.com/questions/53526860/sending-file-from-server-to-server-using-axios

**Comment by RubenVerborgh** [comment]
@rwpino Thanks, replied there.
