### ISSUE TITLE
This no longer works in NodeJS 9.0

### ISSUE THREAD

**Issue by bradennapier** [olalonde/follow-redirects#74]
From waht I can tell reading source, this module is at fault for axios no longer working after upgrading to 9.0.

Node makes no real reference to what is going on here, but the error is 

```
 [ERR_MISSING_ARGS]: The "value" argument must be specified
```

```
0|developm |     at validateHeader (_http_outgoing.js:501:11)
0|developm |     at ClientRequest.setHeader (_http_outgoing.js:510:3)
0|developm |     at new ClientRequest (_http_client.js:173:14)
0|developm |     at Object.request (https.js:241:10)
0|developm |     at RedirectableRequest._performRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:73:20)
0|developm |     at new RedirectableRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:57:7)
0|developm |     at Object.wrappedProtocol.request (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/follow-redirects/index.js:229:10)
0|developm |     at dispatchHttpRequest (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/axios/lib/adapters/http.js:130:25)
0|developm |     at new Promise (<anonymous>)
0|developm |     at httpAdapter (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-datastream/apps/datastream/node_modules/axios/lib/adapters/http.js:18:10)
```

**Comment by RubenVerborgh** [comment]
All our tests pass on Node.js 9: https://travis-ci.org/olalonde/follow-redirects/jobs/305734117.
Please add more specific steps to reproduce.

**Comment by adibkadir** [comment]
I hitting the same error when making get requests using axios and node v9.6.1.

`[ERR_MISSING_ARGS]: The "value" argument must be specified`

It worked before on node 6.x prior to the upgrade.

**Comment by RubenVerborgh** [comment]
@adibkadir Do you have specific steps to reproduce? Are we sure this isn't an axios bug?

**Comment by adibkadir** [comment]
Just found the problem. It was an axios error. I was passing a null string to the Cookie property in the request header config. The error was just a little hard to understand.

Sorry :)
