### ISSUE TITLE
Protocol mismatch

### ISSUE THREAD

**Issue by phocks** [olalonde/follow-redirects#95]
It seems when a https link redirects to a http address it throws this error.

Probably as expected. I'm just wondering if there's an easy way to get it to switch protocols.

**Comment by phocks** [comment]
Check here. Maybe I'm doing something wrong. Expected behaviour was that https://ab.co/2xStcRm would resolve to http://www.abc.net.au/life/

Click "Status" to show the console https://glitch.com/edit/#!/alabaster-observation?path=server.js:10:21 and check this error:

```assert.js:42

  throw new errors.AssertionError({

  ^


AssertionError [ERR_ASSERTION]: protocol mismatch

    at Object.wrappedProtocol.request (/rbd/pnpm-volume/1b46a896-6ac5-4154-8ae9-1acd5e208cd6/node_modules/.registry.npmjs.org/follow-redirects/1.5.8/node_modules/follow-redirects/index.js:294:14)

    at Object.wrappedProtocol.get (/rbd/pnpm-volume/1b46a896-6ac5-4154-8ae9-1acd5e208cd6/node_modules/.registry.npmjs.org/follow-redirects/1.5.8/node_modules/follow-redirects/index.js:301:37)

at Object.<anonymous> (/app/server.js:7:6)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

    at Function.Module.runMain (module.js:694:10)

    at startup (bootstrap_node.js:204:16)
```

**Comment by RubenVerborgh** [comment]
> Expected behaviour was that `https://ab.co/2xStcRm` would resolve to `http://www.abc.net.au/life/`

And it does, but since that first URL is an HTTPS URL, you need to use the `https` module rather than the `http` module. This follows Node.js core libs.

This works:
```js
const { http, https } = require('follow-redirects');
https.get('https://ab.co/2xStcRm', console.log);
```

This does not, on purpose:
```js
const { http, https } = require('follow-redirects');
http.get('https://ab.co/2xStcRm', console.log);
```
